### ISSUE TITLE
commands not run in some cases

### ISSUE THREAD

**Issue by vtolstov** [drone/drone#1925]
drone 0.5 with sha commit id 928130d
Simple pipeline:
```
pipeline:
  clone:
    image: plugins/git
    depth: 1
    when:
      branch: master
  build:
    image: vtolstov/drone-packer
    devices:
      - "/dev/kvm:/dev/kvm"
    privileged: true
    pull: true
    commands:
      - date
      - CHECKPOINT_DISABLE=1 DESTDIR=/drone/images packer build ${TEMPLATE}.json
      - ls -alo /drone/images/
      - date
matrix:
  TEMPLATE:
    - centos-6-x86_32
```

packer something modify in current environment and then drone run commands only first date output date, after that packer command executed and container successful destroyed.

**Comment by bradrydzewski** [comment]
I am unable to repeat, and this sounds like issues we've had in the past related to docker daemon streaming problems https://github.com/drone/drone/issues/1884

Keep in mind that drone takes your yaml and coverts to a shell script, and then executes this shell script as the entrypoint (below example). This means it is bash, not drone, that is controlling execution.

```
#!/bin/sh
set -e

date
CHECKPOINT_DISABLE=1 DESTDIR=/drone/images packer build ${TEMPLATE}.json
ls -alo /drone/images/
date

exit 0
```

It is therefore likely that docker daemon is not streaming the logs due to issues linked above. It could also be possible that docker does not finish streaming logs before the container is shutdown (although unlikely). In that, this is already resolved in the new [runtime](https://github.com/cncd/runtime) which is the new build runner (not yet public) that will replace the existing running in the next week or so.

**Comment by vtolstov** [comment]
I'm enter to build container while it running and drone shell script contains all lines...
Also i'm try to add sleep with big value after packer command and it does not sleeped.... I'm try retest again, but i think that issue not resolved.
Also note that i have docker 1.12.6.
