### ISSUE TITLE
Feature proposal - conditional matrix builds

### ISSUE THREAD

**Issue by yellowmegaman** [drone/drone#2257]
Hi there!

I'd like to be able to define martix build like this:
```
matrix:
  PACKER_VERSION:
#   - 1.1.0
    - 1.1.1
  CONSUL_VERSION:
    - 1.0.0
    - 0.9.3
  when:
    event: [ "consultest", "deployment" ]

services:
  service-consul:
    image: consul:${CONSUL_VERSION}
    when:
      event: [ "consultest", "deployment" ]
```

Right now it ends with `yaml: unmarshal errors: line 140: cannot unmarshal !!map into []string`

So i'd like to run an event that is matrix-enabled, but don't use this matrix for main build.
This is great if you're planning to use events as custom testing cases, not activated all the time.
Hope i'm just missing something ;)

Thanks a lot in advance!

**Comment by tboerger** [comment]
The list of available events is fixed and not configurable.

**Comment by yellowmegaman** [comment]
Hi! 
Maybe i did get your answer wrong, but I'm talking about running matrix with `when` block.

**Comment by tboerger** [comment]
Since the events are pre-defined this won't be possible.

**Comment by yellowmegaman** [comment]
@tboerger Thank you for trying to help, but i really still don't get it really. Maybe it would be easier if you take a glance at the pipeline code and point which segment is `pre-defined`

```
pipeline:

  some-build:
    image: debian:buster
    commands:
      - env | sort
    when:
      event: [push, pull_request]

  consul-test:
    image: debian:buster
    commands:
      - apt-get update && apt-get install curl -y
      - curl -v http://consul-service:8500/v1/status/leader
    when:
      event: [ "coco", "deployment" ]

matrix:
  CONSUL_VERSION:
    - 1.0.0
    - 0.9.3
when:
  event: [ "coco", "deployment" ]

services:
  consul-service:
    image: consul:${CONSUL_VERSION}
    when:
      event: [ "coco", "deployment" ]
```

So `some-build` is executed 2 times, for `1.0.0` and `0.9.3` versions of consul.
Event `coco` is also executed in the same fashion.
Matrix section has `when` block, which is ignored.
What i'm trying to achieve:
-  step `some-build` executed only once
-  then, for example, i store build artifact in s3
-  then i test it against `1.0.0` and `0.9.3` versions of consul

Maybe there's lot better practice, which i'm unaware of, which allows to build once and test against different versions of some software, and also be user-triggered.
Whole scenario intended to be more complex and run only when needed, not part of daily pipeline.

Any thoughts? Thanks a lot for patience =)

**Comment by bradrydzewski** [comment]
Instead of using matrix builds, you could do something like this:

```
pipeline:
  some-build:
    image: debian:buster
    commands:
      - env | sort
    when:
      event: [push, pull_request]

  consul-test-1:
    image: golang
    commands:
      - curl -v http://consul10:8500/v1/status/leader

  consul-test-2:
    image: golang
    commands:
      - curl -v http://consul09:8500/v1/status/leader

services:
  consul10:
    image: consul:1.0.0
  consul09:
    image: consul:0.9.3
```

I personally dislike matrix builds. It is not possible to share artifacts between matrix builds or fan back in once matrix builds complete and execute post-matrix steps. The above yaml has both of these capabilities and achieves the same goal as the matrix build, without using matrixes.

**Comment by yellowmegaman** [comment]
Thanks a bunch, glad there's always a way, and seems just a nice one!
